/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as StreamsIndexRouteImport } from './routes/streams/index'
import { Route as SnapshotsIndexRouteImport } from './routes/snapshots/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RetentionIndexRouteImport } from './routes/retention/index'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities/index'
import { Route as CompactionIndexRouteImport } from './routes/compaction/index'
import { Route as ClusterIndexRouteImport } from './routes/cluster/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as BrokersIndexRouteImport } from './routes/brokers/index'
import { Route as TopicsTopicRouteImport } from './routes/topics/$topic'
import { Route as StreamsStreamIdRouteImport } from './routes/streams/$streamId'
import { Route as BrokersBrokerIdRouteImport } from './routes/brokers/$brokerId'
import { Route as EntitiesEntityTypeIndexRouteImport } from './routes/entities/$entityType/index'
import { Route as TopicsTopicTimelineRouteImport } from './routes/topics/$topic_.timeline'
import { Route as EntitiesEntityTypeEntityIdRouteImport } from './routes/entities/$entityType/$entityId'
import { Route as EntitiesEntityTypeEntityIdTimelineRouteImport } from './routes/entities/$entityType/$entityId_.timeline'
import { Route as BrokersBrokerIdTopicsTopicRouteImport } from './routes/brokers/$brokerId_.topics.$topic'
import { Route as BrokersBrokerIdTopicsTopicPlaygroundRouteImport } from './routes/brokers/$brokerId_.topics.$topic_.playground'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsIndexRoute = StreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsIndexRoute = SnapshotsIndexRouteImport.update({
  id: '/snapshots/',
  path: '/snapshots/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionIndexRoute = RetentionIndexRouteImport.update({
  id: '/retention/',
  path: '/retention/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/entities/',
  path: '/entities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompactionIndexRoute = CompactionIndexRouteImport.update({
  id: '/compaction/',
  path: '/compaction/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterIndexRoute = ClusterIndexRouteImport.update({
  id: '/cluster/',
  path: '/cluster/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersIndexRoute = BrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsStreamIdRoute = StreamsStreamIdRouteImport.update({
  id: '/streams/$streamId',
  path: '/streams/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersBrokerIdRoute = BrokersBrokerIdRouteImport.update({
  id: '/brokers/$brokerId',
  path: '/brokers/$brokerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeIndexRoute = EntitiesEntityTypeIndexRouteImport.update({
  id: '/entities/$entityType/',
  path: '/entities/$entityType/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicTimelineRoute = TopicsTopicTimelineRouteImport.update({
  id: '/topics/$topic_/timeline',
  path: '/topics/$topic/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesEntityTypeEntityIdRoute =
  EntitiesEntityTypeEntityIdRouteImport.update({
    id: '/entities/$entityType/$entityId',
    path: '/entities/$entityType/$entityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EntitiesEntityTypeEntityIdTimelineRoute =
  EntitiesEntityTypeEntityIdTimelineRouteImport.update({
    id: '/entities/$entityType/$entityId_/timeline',
    path: '/entities/$entityType/$entityId/timeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrokersBrokerIdTopicsTopicRoute =
  BrokersBrokerIdTopicsTopicRouteImport.update({
    id: '/brokers/$brokerId_/topics/$topic',
    path: '/brokers/$brokerId/topics/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrokersBrokerIdTopicsTopicPlaygroundRoute =
  BrokersBrokerIdTopicsTopicPlaygroundRouteImport.update({
    id: '/brokers/$brokerId_/topics/$topic_/playground',
    path: '/brokers/$brokerId/topics/$topic/playground',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/brokers/': typeof BrokersIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/cluster/': typeof ClusterIndexRoute
  '/compaction/': typeof CompactionIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/health/': typeof HealthIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/retention/': typeof RetentionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/streams/': typeof StreamsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/entities/$entityType/$entityId': typeof EntitiesEntityTypeEntityIdRoute
  '/topics/$topic/timeline': typeof TopicsTopicTimelineRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/brokers/$brokerId/topics/$topic': typeof BrokersBrokerIdTopicsTopicRoute
  '/entities/$entityType/$entityId/timeline': typeof EntitiesEntityTypeEntityIdTimelineRoute
  '/brokers/$brokerId/topics/$topic/playground': typeof BrokersBrokerIdTopicsTopicPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/brokers': typeof BrokersIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/cluster': typeof ClusterIndexRoute
  '/compaction': typeof CompactionIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/health': typeof HealthIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/retention': typeof RetentionIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/snapshots': typeof SnapshotsIndexRoute
  '/streams': typeof StreamsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/entities/$entityType/$entityId': typeof EntitiesEntityTypeEntityIdRoute
  '/topics/$topic/timeline': typeof TopicsTopicTimelineRoute
  '/entities/$entityType': typeof EntitiesEntityTypeIndexRoute
  '/brokers/$brokerId/topics/$topic': typeof BrokersBrokerIdTopicsTopicRoute
  '/entities/$entityType/$entityId/timeline': typeof EntitiesEntityTypeEntityIdTimelineRoute
  '/brokers/$brokerId/topics/$topic/playground': typeof BrokersBrokerIdTopicsTopicPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brokers/$brokerId': typeof BrokersBrokerIdRoute
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/brokers/': typeof BrokersIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/cluster/': typeof ClusterIndexRoute
  '/compaction/': typeof CompactionIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/health/': typeof HealthIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/retention/': typeof RetentionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/snapshots/': typeof SnapshotsIndexRoute
  '/streams/': typeof StreamsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/entities/$entityType/$entityId': typeof EntitiesEntityTypeEntityIdRoute
  '/topics/$topic_/timeline': typeof TopicsTopicTimelineRoute
  '/entities/$entityType/': typeof EntitiesEntityTypeIndexRoute
  '/brokers/$brokerId_/topics/$topic': typeof BrokersBrokerIdTopicsTopicRoute
  '/entities/$entityType/$entityId_/timeline': typeof EntitiesEntityTypeEntityIdTimelineRoute
  '/brokers/$brokerId_/topics/$topic_/playground': typeof BrokersBrokerIdTopicsTopicPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brokers/$brokerId'
    | '/streams/$streamId'
    | '/topics/$topic'
    | '/brokers/'
    | '/catalog/'
    | '/cluster/'
    | '/compaction/'
    | '/entities/'
    | '/health/'
    | '/metrics/'
    | '/retention/'
    | '/settings/'
    | '/snapshots/'
    | '/streams/'
    | '/topics/'
    | '/entities/$entityType/$entityId'
    | '/topics/$topic/timeline'
    | '/entities/$entityType/'
    | '/brokers/$brokerId/topics/$topic'
    | '/entities/$entityType/$entityId/timeline'
    | '/brokers/$brokerId/topics/$topic/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brokers/$brokerId'
    | '/streams/$streamId'
    | '/topics/$topic'
    | '/brokers'
    | '/catalog'
    | '/cluster'
    | '/compaction'
    | '/entities'
    | '/health'
    | '/metrics'
    | '/retention'
    | '/settings'
    | '/snapshots'
    | '/streams'
    | '/topics'
    | '/entities/$entityType/$entityId'
    | '/topics/$topic/timeline'
    | '/entities/$entityType'
    | '/brokers/$brokerId/topics/$topic'
    | '/entities/$entityType/$entityId/timeline'
    | '/brokers/$brokerId/topics/$topic/playground'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brokers/$brokerId'
    | '/streams/$streamId'
    | '/topics/$topic'
    | '/brokers/'
    | '/catalog/'
    | '/cluster/'
    | '/compaction/'
    | '/entities/'
    | '/health/'
    | '/metrics/'
    | '/retention/'
    | '/settings/'
    | '/snapshots/'
    | '/streams/'
    | '/topics/'
    | '/entities/$entityType/$entityId'
    | '/topics/$topic_/timeline'
    | '/entities/$entityType/'
    | '/brokers/$brokerId_/topics/$topic'
    | '/entities/$entityType/$entityId_/timeline'
    | '/brokers/$brokerId_/topics/$topic_/playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrokersBrokerIdRoute: typeof BrokersBrokerIdRoute
  StreamsStreamIdRoute: typeof StreamsStreamIdRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  BrokersIndexRoute: typeof BrokersIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ClusterIndexRoute: typeof ClusterIndexRoute
  CompactionIndexRoute: typeof CompactionIndexRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  RetentionIndexRoute: typeof RetentionIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SnapshotsIndexRoute: typeof SnapshotsIndexRoute
  StreamsIndexRoute: typeof StreamsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  EntitiesEntityTypeEntityIdRoute: typeof EntitiesEntityTypeEntityIdRoute
  TopicsTopicTimelineRoute: typeof TopicsTopicTimelineRoute
  EntitiesEntityTypeIndexRoute: typeof EntitiesEntityTypeIndexRoute
  BrokersBrokerIdTopicsTopicRoute: typeof BrokersBrokerIdTopicsTopicRoute
  EntitiesEntityTypeEntityIdTimelineRoute: typeof EntitiesEntityTypeEntityIdTimelineRoute
  BrokersBrokerIdTopicsTopicPlaygroundRoute: typeof BrokersBrokerIdTopicsTopicPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/': {
      id: '/streams/'
      path: '/streams'
      fullPath: '/streams/'
      preLoaderRoute: typeof StreamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots/': {
      id: '/snapshots/'
      path: '/snapshots'
      fullPath: '/snapshots/'
      preLoaderRoute: typeof SnapshotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention/': {
      id: '/retention/'
      path: '/retention'
      fullPath: '/retention/'
      preLoaderRoute: typeof RetentionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/entities'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compaction/': {
      id: '/compaction/'
      path: '/compaction'
      fullPath: '/compaction/'
      preLoaderRoute: typeof CompactionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/': {
      id: '/cluster/'
      path: '/cluster'
      fullPath: '/cluster/'
      preLoaderRoute: typeof ClusterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/': {
      id: '/brokers/'
      path: '/brokers'
      fullPath: '/brokers/'
      preLoaderRoute: typeof BrokersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$streamId': {
      id: '/streams/$streamId'
      path: '/streams/$streamId'
      fullPath: '/streams/$streamId'
      preLoaderRoute: typeof StreamsStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$brokerId': {
      id: '/brokers/$brokerId'
      path: '/brokers/$brokerId'
      fullPath: '/brokers/$brokerId'
      preLoaderRoute: typeof BrokersBrokerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/': {
      id: '/entities/$entityType/'
      path: '/entities/$entityType'
      fullPath: '/entities/$entityType/'
      preLoaderRoute: typeof EntitiesEntityTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic_/timeline': {
      id: '/topics/$topic_/timeline'
      path: '/topics/$topic/timeline'
      fullPath: '/topics/$topic/timeline'
      preLoaderRoute: typeof TopicsTopicTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$entityId': {
      id: '/entities/$entityType/$entityId'
      path: '/entities/$entityType/$entityId'
      fullPath: '/entities/$entityType/$entityId'
      preLoaderRoute: typeof EntitiesEntityTypeEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/$entityType/$entityId_/timeline': {
      id: '/entities/$entityType/$entityId_/timeline'
      path: '/entities/$entityType/$entityId/timeline'
      fullPath: '/entities/$entityType/$entityId/timeline'
      preLoaderRoute: typeof EntitiesEntityTypeEntityIdTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$brokerId_/topics/$topic': {
      id: '/brokers/$brokerId_/topics/$topic'
      path: '/brokers/$brokerId/topics/$topic'
      fullPath: '/brokers/$brokerId/topics/$topic'
      preLoaderRoute: typeof BrokersBrokerIdTopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$brokerId_/topics/$topic_/playground': {
      id: '/brokers/$brokerId_/topics/$topic_/playground'
      path: '/brokers/$brokerId/topics/$topic/playground'
      fullPath: '/brokers/$brokerId/topics/$topic/playground'
      preLoaderRoute: typeof BrokersBrokerIdTopicsTopicPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrokersBrokerIdRoute: BrokersBrokerIdRoute,
  StreamsStreamIdRoute: StreamsStreamIdRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  BrokersIndexRoute: BrokersIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ClusterIndexRoute: ClusterIndexRoute,
  CompactionIndexRoute: CompactionIndexRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  RetentionIndexRoute: RetentionIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SnapshotsIndexRoute: SnapshotsIndexRoute,
  StreamsIndexRoute: StreamsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  EntitiesEntityTypeEntityIdRoute: EntitiesEntityTypeEntityIdRoute,
  TopicsTopicTimelineRoute: TopicsTopicTimelineRoute,
  EntitiesEntityTypeIndexRoute: EntitiesEntityTypeIndexRoute,
  BrokersBrokerIdTopicsTopicRoute: BrokersBrokerIdTopicsTopicRoute,
  EntitiesEntityTypeEntityIdTimelineRoute:
    EntitiesEntityTypeEntityIdTimelineRoute,
  BrokersBrokerIdTopicsTopicPlaygroundRoute:
    BrokersBrokerIdTopicsTopicPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
